version: '3.2'

services:

  redis:
    image: "redis:alpine"
    command: redis-server
    expose:
      - "6379"
    volumes:
      - $PWD/redis/data:/data
      - $PWD/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      gateway_net:
        ipv4_address: 172.16.1.1

  mosquitto:
    image: "eclipse-mosquitto:2"
    expose:
      - "1883"
    volumes:
      - $PWD/mosquitto/data:/mosquitto/data
      - $PWD/mosquitto/log:/mosquitto/log
      - $PWD/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      gateway_net:
        ipv4_address: 172.16.1.2

networks:
  gateway_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
